"""add_ticker_ingestion_runs_nullable_source

Revision ID: 03673749c49d
Revises: 8011ca647fef
Create Date: 2026-03-22 00:39:28.656326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03673749c49d'
down_revision: Union[str, None] = '8011ca647fef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('feed_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('items_fetched', sa.Integer(), nullable=False),
    sa.Column('items_deduped', sa.Integer(), nullable=False),
    sa.Column('accounts_created', sa.Integer(), nullable=False),
    sa.Column('accounts_existing', sa.Integer(), nullable=False),
    sa.Column('raw_events_created', sa.Integer(), nullable=False),
    sa.Column('signals_created', sa.Integer(), nullable=False),
    sa.Column('signals_skipped', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('skip_reasons', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_runs_feed_type'), 'ingestion_runs', ['feed_type'], unique=False)
    op.create_index(op.f('ix_ingestion_runs_workspace_id'), 'ingestion_runs', ['workspace_id'], unique=False)
    op.add_column('accounts', sa.Column('ticker', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_accounts_ticker'), 'accounts', ['ticker'], unique=False)
    op.alter_column('raw_events', 'account_source_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('raw_events', 'account_source_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_accounts_ticker'), table_name='accounts')
    op.drop_column('accounts', 'ticker')
    op.drop_index(op.f('ix_ingestion_runs_workspace_id'), table_name='ingestion_runs')
    op.drop_index(op.f('ix_ingestion_runs_feed_type'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    # ### end Alembic commands ###
